const MINOR_ACTION = 'minor';
const MOVE_ACTION = 'move';
const STANDARD_ACTION = 'standard';
const FULL_ROUND_ACTION = 'fullRound';
const FREE_ACTION = 'free';
const SWIFT_ACTION = 'swift';
const AOO_ACTION = 'aoo';

const ACTION_ECONOMY_TYPES = [
  FREE_ACTION,
  SWIFT_ACTION,
  MINOR_ACTION,
  MOVE_ACTION,
  STANDARD_ACTION,
  FULL_ROUND_ACTION,
  AOO_ACTION,
] as const;

type ActionEconomyType = typeof ACTION_ECONOMY_TYPES[number];

const ACTION_ECONOMY: Record<string, ActionEconomyType> = {
  MINOR: MINOR_ACTION,
  MOVE: MOVE_ACTION,
  STANDARD: STANDARD_ACTION,
  FULL_ROUND: FULL_ROUND_ACTION,
  FREE: FREE_ACTION,
  SWIFT: SWIFT_ACTION,
  AOO: AOO_ACTION,
};

export {
  ACTION_ECONOMY,
  ACTION_ECONOMY_TYPES,
  AOO_ACTION,
  FREE_ACTION,
  FULL_ROUND_ACTION,
  MINOR_ACTION,
  MOVE_ACTION,
  STANDARD_ACTION,
  SWIFT_ACTION,
};

export type {
  ActionEconomyType,
};
