const UNARMED_WEAPON_SUBCATEGORY = 'unarmed';
const MAIN_OR_OFF_WEAPON_SUBCATEGORY = 'mainOrOff';
const TWO_HANDED_WEAPON_SUBCATEGORY = 'twoHanded';
const MAIN_ONLY_WEAPON_SUBCATEGORY = 'mainOnly';
const OFF_ONLY_WEAPON_SUBCATEGORY = 'offOnly';
const RANGED_WEAPON_SUBCATEGORY = 'ranged';
const OTHER_WEAPON_SUBCATEGORY = 'other';
const WEAPON_SUBCATEGORIES = new Set([
  UNARMED_WEAPON_SUBCATEGORY,
  MAIN_OR_OFF_WEAPON_SUBCATEGORY,
  TWO_HANDED_WEAPON_SUBCATEGORY,
  MAIN_ONLY_WEAPON_SUBCATEGORY,
  OFF_ONLY_WEAPON_SUBCATEGORY,
  RANGED_WEAPON_SUBCATEGORY,
  OTHER_WEAPON_SUBCATEGORY,
] as const);
const WEAPON_SUBCATEGORY = {
  UNARMED_WEAPON_SUBCATEGORY,
  MAIN_OR_OFF_WEAPON_SUBCATEGORY,
  TWO_HANDED_WEAPON_SUBCATEGORY,
  MAIN_ONLY_WEAPON_SUBCATEGORY,
  OFF_ONLY_WEAPON_SUBCATEGORY,
  RANGED_WEAPON_SUBCATEGORY,
  OTHER_WEAPON_SUBCATEGORY,
} as const;
type WeaponSubcategory = (typeof WEAPON_SUBCATEGORY)[keyof typeof WEAPON_SUBCATEGORY];


const SUBCATEGORY_LABELS = {
  [UNARMED_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.unarmed',
  [MAIN_OR_OFF_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.mainOrOff',
  [TWO_HANDED_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.twoHanded',
  [MAIN_ONLY_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.mainOnly',
  [OFF_ONLY_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.offOnly',
  [RANGED_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.ranged',
  [OTHER_WEAPON_SUBCATEGORY]: 'dnd35e.ACTOR.inventory.subcategory.other',
} as const;

const SUBCATEGORY_ORDER = {
  [UNARMED_WEAPON_SUBCATEGORY]: 0,
  [MAIN_OR_OFF_WEAPON_SUBCATEGORY]: 1,
  [TWO_HANDED_WEAPON_SUBCATEGORY]: 2,
  [MAIN_ONLY_WEAPON_SUBCATEGORY]: 3,
  [OFF_ONLY_WEAPON_SUBCATEGORY]: 4,
  [RANGED_WEAPON_SUBCATEGORY]: 5,
  [OTHER_WEAPON_SUBCATEGORY]: 99,
} as const;

export type {
  WeaponSubcategory,
};

export {
  SUBCATEGORY_LABELS,
  SUBCATEGORY_ORDER,
  WEAPON_SUBCATEGORIES,
  WEAPON_SUBCATEGORY,
};